version: '3.5'

services:
  db:
    image: postgres
    container_name: parking_control
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - parking_control_data:/var/lib/postegres
    mem_limit: 512m


volumes:
  parking_control_data: